<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WinOpt</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\src\WinServerOPT\BrandPalette.cs" Link="BrandPalette.cs" />
  </ItemGroup>
</Project>
