<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>SrvDesk</AssemblyName>
    <RootNamespace>WinOpt</RootNamespace>
    <Title>Windows server优化助手SrvDesk</Title>
    <Product>Windows server优化助手SrvDesk</Product>
    <Company>WinOpt</Company>
    <Authors>WinOpt</Authors>
    <Copyright>Copyright (c) 2026 WinOpt</Copyright>
    <Description>Windows Server 与桌面系统设置优化工具</Description>
    <Version>1.0.1</Version>
    <FileVersion>1.0.1.0</FileVersion>
    <InformationalVersion>1.0.1</InformationalVersion>
    <NeutralLanguage>zh-CN</NeutralLanguage>
    <DebugType Condition="'$(Configuration)'=='Release'">pdbonly</DebugType>
    <DebugSymbols Condition="'$(Configuration)'=='Release'">true</DebugSymbols>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.ico" LogicalName="WinOpt.app.ico" />
    <EmbeddedResource Include="app.png" LogicalName="WinOpt.app.png" />
  </ItemGroup>
  <Target Name="RemoveAppConfigAfterBuild" AfterTargets="Build">
    <Delete Files="$(TargetPath).config" Condition="Exists('$(TargetPath).config')" />
  </Target>
  <Target Name="RemoveAppConfigAfterPublish" AfterTargets="Publish">
    <ItemGroup>
      <_ConfigFiles Include="$(PublishDir)**\$(AssemblyName).exe.config" />
    </ItemGroup>
    <Delete Files="@(_ConfigFiles)" />
  </Target>
</Project>
