<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>Win一键优化</AssemblyName>
    <RootNamespace>WinOpt</RootNamespace>
    <Version>1.0.0</Version>
    <Product>Win一键优化</Product>
    <Description>Windows Server 一键优化</Description>
    <DebugType Condition="'$(Configuration)'=='Release'">none</DebugType>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Management" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="app.ico" LogicalName="WinOpt.app.ico" />
    <EmbeddedResource Include="app.png" LogicalName="WinOpt.app.png" />
  </ItemGroup>
  <Target Name="RemoveAppConfigAfterBuild" AfterTargets="Build">
    <Delete Files="$(TargetPath).config" Condition="Exists('$(TargetPath).config')" />
  </Target>
  <Target Name="RemoveAppConfigAfterPublish" AfterTargets="Publish">
    <ItemGroup>
      <_ConfigFiles Include="$(PublishDir)**\$(AssemblyName).exe.config" />
    </ItemGroup>
    <Delete Files="@(_ConfigFiles)" />
  </Target>
</Project>
