<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>Win一键优化</AssemblyName>
    <RootNamespace>WinOpt</RootNamespace>
    <Version>1.0.0</Version>
    <Product>Win一键优化</Product>
    <Description>Windows Server 一键优化</Description>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType Condition="'$(Configuration)'=='Release'">none</DebugType>
  </PropertyGroup>
</Project>
